"""empty message

Revision ID: 6deb15f03c54
Revises: 
Create Date: 2018-09-12 10:12:57.712070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6deb15f03c54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('batch_code', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=2), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('batch_code')
    )
    op.create_table('faculty',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('faculty_id')
    )
    op.create_index(op.f('ix_faculty_username'), 'faculty', ['username'], unique=True)
    op.create_table('schedule',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('batch_code', sa.Integer(), nullable=True),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['batch_code'], ['batches.batch_code'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.faculty_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('students',
    sa.Column('roll_no', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['batch_code'], ['batches.batch_code'], ),
    sa.PrimaryKeyConstraint('roll_no')
    )
    op.create_table('attendance',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('date_and_time', sa.DateTime(), nullable=True),
    sa.Column('week_no', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('roll_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.faculty_id'], ),
    sa.ForeignKeyConstraint(['roll_no'], ['students.roll_no'], ),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('students')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_faculty_username'), table_name='faculty')
    op.drop_table('faculty')
    op.drop_table('batches')
    # ### end Alembic commands ###
